Optional Pan for mutate/spawn per #82
trioderegion/warpgate pull request #98
Opened 2022-11-17 11:11 UTC by jabarri1

Attempt at setting up an optional Pan as requested in Issue #82 as well as some minor spelling changes I spotted randomly.

2022-11-18 15:09 UTC, trioderegion commented
Hi there! Thanks so much for your contribution. While this approach does address the use-case, the implementation doesn't *quite* fit with the reworked options/workflow options.

I will add some review comments if you are up for a refactor, but if not, no worries, this provides a starting point for me if nothing else.

2022-11-18 15:52 UTC, trioderegion requested changes

2022-11-18 15:52 UTC, trioderegion commented on lang/en.json
> +      },
Unneeded after refactor

2022-11-18 15:52 UTC, trioderegion commented on scripts/api.js
> +    if(MODULE.setting('spawnPan')) await MODULE.panToToken(spawnLocation);
Instead of checking for a module setting, pass a `pan: true` or `pan: {pan, settings}` in the `SpawningOptions` option type.

Additionally, remove the pan operation from here, we will be panning just prior to spawning (line 503, ONLY IF this is the first iteration).

2022-11-18 15:52 UTC, trioderegion commented on scripts/mutator.js
> +    MODULE.applySettings(settingsData);
panning options moved into the `WorkflowOptions`, similar to panning for spawn.

2022-11-18 15:52 UTC, trioderegion commented on scripts/module.js
> +  }
`canvas.ping` is a v10 only function.  To further complicate things, only the GM can pull.

To implement this feature fully, we need the following:

- [ ] a v9 equivalent
- [ ] allowing either a pan or ping based on `WorkflowOptions` or `SpawningOptions`
- [ ] defer the pan by inserting the pan request into the `SPAWN` and `MUTATE` events (revert calls mutate) and add stock `event.watch` that ONLY the first GM responds to which simply looks for the pan request and does so.
- [ ] Players can ping freely, do not defer this request.

2022-11-18 15:52 UTC, trioderegion commented on scripts/mutator.js
> +    const tokenCenter = canvas.tokens.placeables.find(i => i.id === tokenDoc.id).center;
Current token center can be gotten from `tokenDoc.object?.center` and needs to accomodate for tokens without a placeable object.

The mutate operation may be translating and scaling the token, ensure that we are panning/pinging the correct final location.

2022-11-18 15:52 UTC, trioderegion commented on scripts/mutator.js
> +      if(MODULE.setting('mutatePan')) await MODULE.panToToken({x: tokenCenter.x, y: tokenCenter.y});
Defer panning to GM based on workflow options and event data. Same as spawning.

2022-11-18 15:52 UTC, trioderegion commented on scripts/mutator.js
> +      if(MODULE.setting('mutatePan')) await MODULE.panToToken({x: tokenCenter.x, y: tokenCenter.y});
Remote mutations follow the same workflow as local mutations and the panning taken into account inside `isOwner` block will be executed on the remote client.

This is uneeded.

2022-11-18 23:27 UTC, jabarri1 commented
I'm not quite as js savvy as I'd like to be, but I'm no quitter. I'll give it a shot still. 👍

2022-11-21 07:37 UTC, ChueyB commented
It's not elegant by any means, but it does work.

- [X] v9 equivalent using .animatePan
- [X] Ping and Pan are both options
- [X] Pull pings are done by the firstGM
- [X] animatePan & Regular pings can be done by players
- [ ] Unsure about mutate token scaling. Need to cook up a mutate macro that does this.

2022-11-23 21:03 UTC, ChueyB commented
Confirmed the pan & ping does apply to the center of mutations with width/height changes.

2022-11-27 23:49 UTC, trioderegion commented
Thanks for the update! I will get to this as soon as I can. Many thanks 😃

2023-01-22 03:06 UTC, trioderegion approved these changes

2023-01-22 03:07 UTC, merged